var nombre= 'andrea';
var apellido= 'villada';
var edad= 28;
var fechaDeNacimiento= '31/07/1989';
var direccion= 'pringles';
console.log('nombre: ',nombre);
console.log('apellido: ',apellido);
console.log('edad:', edad);
console.log('fechaDeNacimiento:', fechaDeNacimiento);
console.log('direccion:', direccion);